language: python
cache: pip
python:
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install flit coveralls future-fstrings
  - flit install
script: PYTHONPATH=. pytest --cov=get_version
after_success: coveralls
