dist: xenial
language: python
cache: pip
python:
  - '3.6'
  - '3.7'

install:
  - pip install future-fstrings flit coveralls
  - flit install --deps develop
script:
  - PYTHONPATH=. pytest --cov=get_version --black
  - rst2html.py --halt=2 README.rst >/dev/null
after_success: coveralls
