language: python
python:
  - '3.6'

# 3.7 needs Xenial image because of https://github.com/travis-ci/travis-ci/issues/9069
matrix:
  include:
    - python: '3.7'
      dist: xenial
      sudo: true

install:
  - pip install --upgrade pytest testpath pytest-cov coveralls
script: PYTHONPATH=. pytest --cov=get_version
after_success: coveralls
sudo: false
