[build-system]
requires = ['flit-core>=2,<4', 'dunamai']
build-backend = 'flit_core.buildapi'

[tool.flit.metadata]
module = 'get_version'
author = 'Philipp Angerer'
author-email = 'phil.angerer@gmail.com'
home-page = 'https://github.com/flying-sheep/get_version'
classifiers = [
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
]
requires-python = '>=3.7'
requires = [
    'dunamai',  # Version parsing
]
description-file = 'README.rst'

[tool.flit.metadata.requires-extra]
test = [
    'pytest',
    'pytest-cov',
    'pytest-black; python_version != "3.5"',
    'pygments',  # for README highlighting check
]

[tool.black]
include = '\.pyi?$'
