[build-system]
requires = ['flit>=1.3']
build-backend = 'flit.buildapi'

[tool.flit.metadata]
module = 'get_version'
author = 'Philipp Angerer'
author-email = 'phil.angerer@gmail.com'
home-page = 'https://github.com/flying-sheep/get_version'
classifiers = [
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
]
requires-python = '>=3.6'
requires = ['setuptools']
description-file = 'README.rst'

[tool.flit.metadata.requires-extra]
test = [
    'pytest',
    'pytest-cov',
    'pytest-black; python_version != "3.5"',
    'testpath',
    'pygments',  # for README highlighting check
]

[tool.black]
py36 = true
include = '\.pyi?$'
